### PR TITLE
Feature/goreleaser

### PR DESCRIPTION
**Pull request by KealanM**
This PR will make use of goreleaser and github actions to build binaries and cut a release when you push a tag on master. Totally up to you if you want to accept addresses #1  which I didnt actually see till I went to create and issue for this :)

### CODE REVIEW

**Comment by KealanM** [comment]
Worth adding you can see the result on my forked master. Does a nice job at doing your change logs etc.
https://github.com/KealanM/chaosity/releases

**Comment by bzuelke** [comment]
Awesome contribution @KealanM this is exactly what I wanted. I'll check this out and get this merged in a bit.

**Review by bzuelke — APPROVED** [review]

**Comment by KealanM** [comment]
Still needs a little work but it will do for now. #4 is updating from a s3 bucket I am sure it could be changed to pull from this, have the guts of a script for it and version command.  GoReleaser is pretty nifty, but I will warn you that you only get so many free action minutes(2K if I recall) and storage (0.5GB) on github @flippedbit so you might want to think putting some limits/alerts on both.

**Comment by bzuelke** [comment]
Yea we were actually talking to that point earlier today thinking on either using actions or google cloud build. Think there will be more to come on that topic.

**Pull request merged**
